import React from 'react';
import Head from 'next/head';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

interface RootLayoutProps {
  children: React.ReactNode;
}

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en" style={{ padding: 0, margin: 0 }}>
      <Head>
        <title>Univise</title>
        <link rel="icon" href="/public/favicon.png" />
      </Head>
      <body style={{ padding: 0, margin: 0 }}>
        {children}
      </body>
    </html>
  );
};

export default RootLayout;